# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
fabric.loom.disableObfuscation=true

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.2
	yarn_mappings=26.2+build.1
	loader_version=0.19.3

# Mod Properties
	mod_version = 0.0.2
	maven_group = io.github.itzispyder
	archives_base_name = AutoClicker

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.154.2+26.2
	improperui_minecraft_version=26.1
	improperui_version=0.0.7
